#!/usr/bin/env bash
# transfers a file from a client to a server with scp

# Check if enough parameters are passed
if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
  exit 1
fi

# Set parameters
FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# If SSH key is not provided, use default location
if [ -z "$SSH_KEY" ]; then
  SSH_KEY=~/.ssh/id_rsa
fi

# Disable strict host key checking
scp -o "StrictHostKeyChecking=no" -i "$SSH_KEY" "$FILE_PATH" "$USERNAME"@"$IP":~/"
