#!/usr/bin/env bash
# installs nginx and configures it on a remote server
# Install Nginx
sudo apt-get update && sudo apt-get upgrade && sudo apt-get -y install nginx
sudo service nginx start

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server/listen 80/' /etc/nginx/sites-available/default

# Create a new index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx without using systemctl
service nginx restart

# Verify Nginx is listening on port 80
netstat -tlnp | grep 80

# Test the GET request using curl
curl localhost
