#!/bin/bash

# Check if password argument is provided
if [ -z "$1" ]; then
  echo "Please provide the MySQL root password as an argument"
  exit 1
fi

# Set password variable
PASSWORD=$1

# Set current date variable
DATE=$(date +%d-%m-%Y)

# Dump all MySQL databases to a file named backup.sql
mysqldump -u root -p$PASSWORD --all-databases > backup.sql

# Compress the backup.sql file to a tar.gz archive
tar -czf $DATE.tar.gz backup.sql

# Remove the backup.sql file
rm backup.sql

echo "Backup and compression complete. Archive name: $DATE.tar.gz
