#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.

# The MySQL dump must contain all your MySQL databases
# The MySQL dump must be named backup.sql
# The user to connect to the MySQL database must be root
# The Bash script accepts one argument that is the password used to connect to the MySQL database
mysqldump -u root -p"$1" -A > backup.sql

# The MySQL dump file has to be compressed to a tar.gz archive
# This archive must have the following name format: day-month-year.tar.gz

tar -czvf "$(date +%d-%m-%Y).tar.gz" backup.sql
